# Generated by Django 3.1.7 on 2021-03-23 14:54

from django.db import migrations, models
import pessoa.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubeDeTiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cnpj', models.CharField(max_length=11, unique=True, validators=[pessoa.validators.validate_cnpj], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'clube de tiro',
                'verbose_name_plural': 'clubes de tiro',
                'db_table': 'clube_de_tiro',
                'ordering': ('-data_cadastro',),
            },
        ),
    ]
