# Generated by Django 3.1.7 on 2021-03-29 00:18

from django.db import migrations, models
import django.db.models.deletion
import pessoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210328_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubedetiro',
            name='cnpj',
            field=models.CharField(max_length=11, unique=True, validators=[pessoa.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.CreateModel(
            name='ModelClubeEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clubedetiro')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
            options={
                'verbose_name': 'clube endereco',
                'verbose_name_plural': 'clube e endereços',
                'db_table': 'clube_endereco',
                'ordering': ('-data_cadastro',),
            },
        ),
    ]
