# Generated by Django 3.1.7 on 2021-03-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210328_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelClubeEndereco',
            new_name='ClubeEndereco',
        ),
    ]
