# Generated by Django 3.1.7 on 2021-04-02 23:32

from django.db import migrations, models
import django.db.models.deletion
import pessoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20210402_2032'),
        ('core', '0004_auto_20210330_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoClube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'endereco do clube',
                'verbose_name_plural': 'enderecos do clube',
                'db_table': 'endereco_clube',
                'ordering': ('-data_cadastro',),
            },
        ),
        migrations.AlterField(
            model_name='clubedetiro',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[pessoa.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.DeleteModel(
            name='ClubeEndereco',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.AddField(
            model_name='enderecoclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clubedetiro'),
        ),
    ]
