# Generated by Django 3.1.7 on 2021-03-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='descrição')),
                ('marca', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'arma',
                'verbose_name_plural': 'armas',
                'db_table': 'arma',
                'ordering': ('-data_cadastro',),
            },
        ),
    ]
