# Generated by Django 3.1.7 on 2021-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='Versao de testes'),
        ),
    ]
