# Generated by Django 3.1.7 on 2021-03-17 01:23

from django.db import migrations, models
import django.db.models.deletion
import pessoa.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, validators=[pessoa.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20)),
                ('pagou', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'db_table': 'pessoa',
                'ordering': ('-data_cadastro',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'endereços',
                'db_table': 'endereco',
                'ordering': ('-data_cadastro',),
            },
        ),
    ]
