# Generated by Django 3.1.7 on 2021-03-17 23:04

from django.db import migrations, models
import pessoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[pessoa.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
