# Generated by Django 3.1.7 on 2021-04-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20210402_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecopessoa',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tenant',
        ),
    ]
